### ISSUE TITLE
Profiling code

### ISSUE THREAD

**Issue by ethanwhite** [weecology/abundance#1]
I figured out how to get `tfprof` outputing  to text files this morning. I sent the files over Slack. The code to generate these files is below.

Some modifications to fitting the model to store the necessary data: 

```
# Fit the model
n = 16
run_metadata = tf.RunMetadata()
for i in range(5):
    _ = sess.run(train_step, feed_dict=make_minibatch(n),
             options=tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE),
             run_metadata=run_metadata)
    n_steps += 1
```

And code to generate the output:

```
opts = tf.contrib.tfprof.model_analyzer.PRINT_ALL_TIMING_MEMORY.copy()

# Profile time and dump results to file
opts['order_by'] = 'micros'
opts['select'] = ['micros', 'occurrence']
opts['max_depth'] = 20
opts['dump_to_file'] = 'tfprofout_time.txt'
tf.contrib.tfprof.model_analyzer.print_model_analysis(
    tf.get_default_graph(),
    run_meta=run_metadata,
    tfprof_options=opts)

# Profile memory and dump results to file
opts['order_by'] = 'bytes'
opts['select'] = ['bytes', 'occurrence']
opts['max_depth'] = 20
opts['dump_to_file'] = 'tfprofout_memory.txt'
tf.contrib.tfprof.model_analyzer.print_model_analysis(
    tf.get_default_graph(),
    run_meta=run_metadata,
    tfprof_options=opts)
```

If you put the two different profiling blocks in different cells you will also see their output as properly sorted JSON in the output cell of the notebook.

**Comment by davharris** [comment]
Thanks @ethanwhite! 

Some of the results you Slacked me for CPU time don't look like I expected (e.g. it says that 40% of the CPU time is from a simple logistic function, if I'm reading correctly). I think that running it longer will give results that are less noisy.  Will see what I can do this weekend.

Thanks again, this will be so much more useful than my gut feelings about what's slow.
